cache:
  yarn: true
  directories:
    - node_modules
language: node_js
sudo: required
node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn install
- bower install
script:
- xvfb-run wct --expanded
after_script:
- cat $TRAVIS_BUILD_DIR/logs/coverage/lcov.info | ./node_modules/.bin/coveralls
dist: trusty