cache:
  directories:
    - node_modules
language: node_js
sudo: required
node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
before_script:
- bower install
script:
- eslint . --ext js,html
- xvfb-run wct --expanded --plugin istanbul --plugin xunit-reporter
- cat ./logs/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- polymer analyze > analysis.json
- polymer build

dist: trusty