cache:
  directories:
    - node_modules
language: node_js
sudo: required
node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/default
  on:
    branch: master
before_script:
- bower install
- polymer analyze > analysis.json
script:
- xvfb-run polymer test --expanded
dist: trusty