cache:
  directories:
    - node_modules
language: node_js
sudo: required
node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
before_script:
- bower install
script:
- eslint . --ext js,html
- xvfb-run wct --expanded
- ls
- xvfb-run ./node_modules/web-component-tester/bin/wct --expanded
- ls
- cat $TRAVIS_BUILD_DIR/logs/coverage/lcov.info | ./node_modules/.bin/coveralls
- wct --plugin sauce
- polymer analyze > analysis.json
- polymer build

dist: trusty